# -*- coding: utf-8 -*-
"""Calculador de couta de credito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DGNKHpnfKkcIwxC1Q2ebJTVpnXe89GM
"""

# Importamos las librerías necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Función para calcular la cuota de un crédito
def calcular_cuota_credito(monto, tasa_interes_anual, num_cuotas):
    tasa_mensual = tasa_interes_anual / 12 / 100
    cuota = monto * (tasa_mensual * (1 + tasa_mensual)**num_cuotas) / ((1 + tasa_mensual)**num_cuotas - 1)
    return cuota

# Función para generar la tabla de amortización
def generar_tabla_amortizacion(monto, tasa_interes_anual, num_cuotas):
    cuota = calcular_cuota_credito(monto, tasa_interes_anual, num_cuotas)
    saldo_inicial = monto
    tabla = []

    for i in range(1, num_cuotas + 1):
        interes = saldo_inicial * (tasa_interes_anual / 12 / 100)
        capital = cuota - interes
        saldo_final = saldo_inicial - capital
        tabla.append([i, saldo_inicial, cuota, capital, interes, saldo_final])
        saldo_inicial = saldo_final

    return pd.DataFrame(tabla, columns=["Mes", "Saldo Inicial", "Cuota", "Capital", "Interés", "Saldo Final"])

# Solicitar datos al usuario
monto = float(input("Ingresa el monto del crédito: "))
tasa_interes_anual = float(input("Ingresa la tasa de interés anual (en %): "))
num_cuotas = int(input("Ingresa el número de cuotas: "))

# Generar la tabla de amortización
tabla_amortizacion = generar_tabla_amortizacion(monto, tasa_interes_anual, num_cuotas)

# Mostrar la tabla de amortización
print("\nTabla de Amortización:")
print(tabla_amortizacion)

# Graficar la amortización
plt.figure(figsize=(10, 6))
plt.plot(tabla_amortizacion["Mes"], tabla_amortizacion["Capital"], label="Capital")
plt.plot(tabla_amortizacion["Mes"], tabla_amortizacion["Interés"], label="Interés")
plt.plot(tabla_amortizacion["Mes"], tabla_amortizacion["Saldo Final"], label="Saldo Final")
plt.title("Amortización del Crédito")
plt.xlabel("Mes")
plt.ylabel("Monto en $")
plt.legend()
plt.grid(True)
plt.show()